### PR TITLE
ignore .htaccess files when syncing files dir

### PR DESCRIPTION
**Pull request by njbarrett**
We shouldn't sync the htaccess files.

### CODE REVIEW

**Comment by jorgegc** [comment]
I don't think the .htaccess inside files cause any harm but I might be wrong. Can you please elaborate? Perhaps explain the issues you are experiencing?

**Comment by njbarrett** [comment]
A couple of times I have run phing files:sync and everything copied fine except for the .htaccess files. I had received some "Permission denied: Operation not permitted" errors, probably because the file permissions on the htaccess files are different. In any case, when I delete them Drupal automatically recreates them as soon as I reload the page, so it makes sense thats its a drupal generated file similar to the other folders you are excluding like ctools etc

**Comment by jorgegc** [comment]
I am pretty sure I have had this issue before and [this answer from Greg Anderson](http://drupal.stackexchange.com/questions/95194/why-drush-fails-to-rsync-between-my-two-local-instances) helped me figure it out.

Ideally, I would like to keep the exclude list to a minimum. If Greg's answer doesn't help I will think about something else.

**Comment by njbarrett** [comment]
I'm not sure it is the same issue as Greg - if I can reproduce it again I will reopen the issue with more details.

**Pull request closed without merging**
